### ISSUE TITLE
No new tests?? (data-by-modzcta)

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#105]
How can the TOTAL_COVID_TESTS be exactly the same as yesterday in data-by-modzcta (at least for the zips I follow: 10028, 10029 and 10128)? That means no new tests done yesterday, which is impossible given there's always a line outside the citymd in Yorkville, straddling 10028 and 10128. Here are the unchanged total tests for those 3 zips. 

10028: 7,611
10029: 10,159
10128: 13,083

Thank you,
S

**Comment by mmontesanonyc** [comment]
The answer to your question touches on two important issues. First, due to reporting lags, our most recent data are incomplete. There is usually a lag of some days between something occurring (like a test) and it being reported to us. 

Secondly, as we often point out, the difference in daily versions of cumulative files do not represent one day's worth of data. Tests, diagnoses, hospitalizations, and deaths reported yesterday have occurred on many different dates in the past.

When we publish data, we publish it based on the date the event occurred, not the date the event was reported to us - so we may get reports early next week that change our counts of tests (and other events) for days in the past.

We strongly discourage treating the daily differences in cumulative files as daily data – because using report date is prone to misinterpretation.
