### ISSUE TITLE
Total tests don't match between data-by-modzcta.csv and tests.csv files

### ISSUE THREAD

**Issue by dyoung95437** [nychealth/coronavirus-data#109]
When one totals all the tests city-wide from the by zip code breakdown in the data-by-modzcta.csv file uploaded on 8/9/20, one gets a total of 1,682,550 tests. But when one totals all of the tests done so far city wide from the tests.csv file uploaded on 8/9/20, one gets a total of 2,619,816 tests. What accounts for this discrepancy of about 1 million tests between the city-wide and zipcode-based figures? Thanks!

**Comment by mmontesanonyc** [comment]
Good question. A few things account for this difference. First, they are reporting different things — per our metadata in the [Readme](https://github.com/nychealth/coronavirus-data#nyc-coronavirus-disease-2019-covid-19-data), [tests.csv](https://github.com/nychealth/coronavirus-data#testscsv) reports the number of people tested each day, but [data-by-modzcta](https://github.com/nychealth/coronavirus-data#data-by-modzctacsv) reports the total number of people tested. That is, if somebody gets tested yesterday and then again today, then they are counted twice in tests.csv (once on each day) but once in data-by-modzcta.csv. 

Secondly, summing and comparing across files will almost always result in different values, because of missing information. For example, if a test record doesn’t contain correct address information for a patient, then doesn’t get included in the data by modzcta. This is less of an issue with data-by-modzcta.csv and tests.csv because they report different things, but worth being aware of if you're comparing values across files.

**Comment by dyoung95437** [comment]
That's all interesting. So if I have downloaded the data-by-modzcta.csv file on various different dates over time, can I use that data to calculate the positivity rate for the period of time between those dates, or are the numbers so unreliable as to be useless? Also there is a positivity rate included in the file which appears to be calculated using the total number of positive tests and the total number of tests. But if those are off by about 38% from the actual number of cases or tests (the 1.6 million vs. 2.6 million discrepancy I mentioned) that makes one question those numbers too -- should one question them? I ask this largely because, as you likely know, Mayor De Blasio and School Chancellor Carranza have stated that all schools will close again if the city as a whole has a positivity rate of over 3%. And, as you may or may not know, the union of school principals has put out publicly concerns over whether schools should stay open if they operate in neighborhoods with over 3% as well. These figures at this site are the only way for any member of the public to figure out a neighborhood's positivity rate, and they appear to show many parts of the city having over 3%. But are they totally unreliable?

**Comment by dyoung95437** [comment]
Additionally: what would you recommend is the best way to calculate the positivity rate in a particular zip code?

**Comment by mmontesanonyc** [comment]
> So if I have downloaded the data-by-modzcta.csv file on various different dates over time, can I use that data to calculate the positivity rate for the period of time between those dates?

 We discourage this because in a cumulative file, tests _reported_ between two dates are not the same as tests _conducted_ between these two dates. Per [Readme](https://github.com/nychealth/coronavirus-data#report-date-versus-date-of-event) and [other issues logged here](https://github.com/nychealth/coronavirus-data/issues?q=%22report+date%22), we **strongly discourage people interpreting changes to cumulative files as trend data**.

> what would you recommend is the best way to calculate the positivity rate in a particular zip code?

data-by-modzcta.csv includes cumulative percent positive by ZIP. 

> Should one question the numbers?

As stated, the difference between "number of tests" and "number of people tested" is a difference in what they measure, not a discrepancy in values. This doesn't mean one should question the numbers, but rather, understand that they represent different things.  Citywide percent positivity by day is calculated based on the number of people tested over time.  The cumulative percent positivity shown in the map reflects data since March, and counts people only once if they tested positive.

**Comment by ttcgh** [comment]
Is there an existing file, or a way to calculate from existing file(s), the trend in positivity rate by zip code? Apologies if answered elsewhere. Happy to fill in a new issues if this isn't the best place to ask. And lastly, thank you all for working hard on the issues and for providing this data to the public!

**Comment by dyoung95437** [comment]
You may know about this and this probably isn't what you want but have you seen this new stuff NYC Public Health put up that includes trends of positivity rates and new case rates by zip code over a recent 2 week period? Be sure to look at both the map and table visualizations: https://www1.nyc.gov/site/doh/covid/covid-19-data-recent.page

Also the data related to that is on Github here: https://github.com/nychealth/coronavirus-data/blob/master/recent/recent-4-week-by-modzcta.csv

**Comment by ttcgh** [comment]
@dyoung95437 this is great, thanks for sharing! hard to keep track of everything they're making available. I'm still interested to know what positivity rates looked like over time by zip, beyond just the past four weeks. but this is still really useful information.

**Comment by dyoung95437** [comment]
I'm glad you are getting something out of that resource, and I would be very interested in seeing that too so hopefully some one else will answer!

**Comment by dyoung95437** [comment]
BTW, in case this is of assistance, I recently realized how to look at the old verisons of different files here (I'm not too familiar with Github), which you can do by opening the latest update and then clicking on where, near the top right, it says "History" and there's a little Clock icon next to that.

**Comment by ttcgh** [comment]
@dyoung95437 thanks! I'm somewhat familiar with git, and would be happy to chat if you ever want to learn more. thanks again for sharing the above resources!

**Comment by dyoung95437** [comment]
Thanks! I may take you up on that. One quick question, is there a way to download a file without having to go to Raw and copy and paste the CSV info into a spreadsheet?

**Comment by ttcgh** [comment]
there are a few ways to do this. gsheets makes it super easy. with just a few lines of code you can do it in R or python. depends on your tool of choice! 

feel free to email me at timcheung.168@gmail.com.

**Comment by dyoung95437** [comment]
Thank you so much! I may be in touch in the future. Take care!
