### ISSUE TITLE
Large decline in test numbers 8/18

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#110]
I know you discourage looking at data every day for daily changes, but the 8/18 upload for data-by-modzcta has a very large decrease in # of tests from yesterday. In 3 of the 5 zip codes I track, declines are in triple digits: 10028 down -228 , 10029 down -454, and 10023 down -576. Those are significant and can't be just minor adjustments.

**Comment by mmontesanonyc** [comment]
That's a good question.

As is normal with surveillance data, data come to us in many different formats and with a wide variety of errors. The data undergo extensive cleaning and processing ​to ensure that each record is as complete as possible, without typos or data entry errors, and not duplicated. 

Test data and case data actually come to us via two different systems. They contain different data and require different cleaning processes. Recently, cleaning processes for the testing dataset were enhanced to bring it in line with other data. 

Because we keep receiving an increasing volume of data, the work to ensure that they are reliable is an ongoing process - thus all data are preliminary and subject to change.
