### ISSUE TITLE
No update 9/6??

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#116]

**Comment by mmontesanonyc** [comment]
Correct. Per [note on the website](https://www1.nyc.gov/site/doh/covid/covid-19-data.page) and the [9/7 commit note](https://github.com/nychealth/coronavirus-data/commit/eac59e5a80628a4aba90460d0cb34c89730532d2), there was no update on 9/6 due to a minor database issue. All data have been updated with the 9/7 update.
