### ISSUE TITLE
Testing drops near ~ 8/18/2020 across all Modified ZCTA's? (can updated historical data be provided?)

### ISSUE THREAD

**Issue by nygeog** [nychealth/coronavirus-data#118]
By comparing across each commit and generating a time-series - if I'm understanding the data correctly, it appears there's a big drop in testing numbers around 8/18/2020. Is there something to explain this? 

![Screen Shot 2020-09-21 at 1 07 37 PM](https://user-images.githubusercontent.com/2790599/93798344-825a0980-fc0b-11ea-980f-185ad7d798fc.png)

Also, looking at one particular MODIFIED_ZCTA it appears the drop is quite a bit. 
![Screen Shot 2020-09-21 at 1 10 10 PM](https://user-images.githubusercontent.com/2790599/93798546-dd8bfc00-fc0b-11ea-8e67-6bdab6a32637.png)

**Comment by nygeog** [comment]
See there's some closed issues on this: https://github.com/nychealth/coronavirus-data/issues/110 and https://github.com/nychealth/coronavirus-data/issues/113 would it be possible to get an update of the historic data?

**Comment by mmontesanonyc** [comment]
Yes, those closed issues address the reason for drops in cumulative counts for certain MODZCTAs. 


> “Would it be possible to get an update of the historical data?”

When we update data in cumulative files, we also update trend data - that is, the revised counts are reflected in the testing data (tests.csv) that show the number of people tested and the number of people tested who test positive each day. 

We have not yet provided these data by modzcta as trend data. We [caution against interpreting the differences in daily cumulative files as daily values](https://github.com/nychealth/coronavirus-data#report-date-versus-date-of-event), as it appears that you have done, since the new data reported one day may have occurred over numerous days in the past - as an update like this shows.
