### ISSUE TITLE
Can more up-to-date positive test rate data be made available to public?

### ISSUE THREAD

**Issue by dyoung95437** [nychealth/coronavirus-data#120]
As this Ocean Parkway Cluster has occurred the news has been citing a lot of up-to-the-minute-ish data on both the positive test rate for the city as a whole and broken down by zipcode, but none of that data seems to be publicly available any where that I know of. Could it be made available at the NYC public health site and this Github portal? Or is it some where else someone can point me too? As someone who follows these numbers closely AND is a resident of an Ocean Parkway Cluster zip code/neighborhood, I'd love to have access to that in order to better understand the best data on what's going on in the city, all of the city. Thanks! BTW I'm referring to city-wide and zipcode numbers like the ones in these two articles -- there's nothing up to date like this available to the public that I've see on the website, only stuff that is accurate only up to 4-10 days back, depending...
https://www.nytimes.com/2020/09/29/nyregion/nyc-coronavirus-uptick.html
https://patch.com/new-york/prospectheights/coronavirus-hotspots-result-bad-local-government-cuomo-says

**Comment by mmontesanonyc** [comment]
Data made available here (and on the website) is published with a 3-day lag. It usually takes several days to get a result from a diagnostic test. We publish data at a lag to ensure that by the time we publish data on tests conducted that day, we are reasonably confident that we are reporting most of the tests conducted that day (since we report tests by the date the test was conducted, not the date its result was reported). Still, on our charts, you'll notice a gray area that indicates that despite this lag, recent data are incomplete because many tests have not yet been reported. The reason we don't publish yesterday's data today is because it's incomplete, and we don't want to mislead people with incomplete data.

Data being reported in the media may come directly from press releases, which you can find [here](https://www1.nyc.gov/site/doh/about/press/covid-19-notices.page).

**Comment by dyoung95437** [comment]
Thanks so much for the helpful explanation and the helpful link on the
press releases. I notice in most areas of the website though that the lag
of reliable info is more like 7-14 days, not 3. Is there any way to improve
that? Especially for the "Recent" zip code data section, which means a lot
to us in the neighborhoods where disease rates are skyrocketing right now?

**Comment by dyoung95437** [comment]
Thanks, that link for the press releases was very helpful but they didn't
put one up on 10/4 as they had every day previously from 9/24 to 10/3. Do
you know when and where that latest data would be available? This of grave
concern to those of us who live in one of the high positivity zip codes
like myself and my wife. Thank you, Dan Young
