### ISSUE TITLE
Updated test.csv data Request

### ISSUE THREAD

**Issue by gneo54** [nychealth/coronavirus-data#125]
It seems like the tests.csv file that was uploaded today has a comment of 10/7 data, but the latest data in the csv file is 10/3.

Can we get this to reflect data up to 10/6? I am looking for the data that powers what the Tableau dashboard publishes and what the mayor publishes.

**Comment by mmontesanonyc** [comment]
Hi, thanks for your question. We publish data in tests.csv with a 3-day lag, meaning the most recent day of data is 3 days prior. That is because we have yet not received information about tests conducted 1 or 2 days ago. In fact, as indicated on the data webpages, the most recent data - up until about a week - is considered incomplete because some tests conducted on those days have not yet been reported to the Health Department. 

This reporting lag is ordinary with surveillance data: when a person gets a COVID-19 test, it takes time for the specimen to go from a medical provider to a laboratory, for the laboratory to conduct the test, and for the laboratory to report the test to the Health Department.

**Comment by gneo54** [comment]
I understand there is a lag. However, 2 questions/requests:

When the mayor communicates today's data which is for yesterday, where does that data come from? can that be published?
Where does the Tableau data come from?  (see https://public.tableau.com/profile/integrated.data.team#!/vizhome/COVID-19UpdatedPublicHealthMilestones/TestinginNYC) 

If you can point me to a data source that is being used in these two scenarios, that would be great.
