### ISSUE TITLE
Zip Code Data not adding up to Total

### ISSUE THREAD

**Issue by davor999** [nychealth/coronavirus-data#126]
When I look at you zip code 4 week data, it shows 633,000 total tests in last 4 weeks, this  is around 160,000 tests per week. However your overall data shows you are testing around 220,000 per week. This suggest a lot of "missing" data in your zip code reports. Can you help explain the gap please?

**Comment by azx65535** [comment]
I also have noticed this issue, which is a big problem for tracking Zip Code level trends.  

More specifically / as an example: 
 - total tests 9/6/20 - 10/5/20 (in the 10/8/20 tests.csv file) totals 939,804 tests
 - cumulative total tests summed across all zip codes in the 10/8/20 data-by-modzcta.csv file totals 2,474,724
 - cumulative total tests summed across all zip codes in the 9/8/20 data-by-modzcta.csv file totals 2,090,800
 - difference in total tests in the data-by-modzcta.csv file is only 383,924 tests, which is only ~40% of the total

Can someone please explain why there is this huge discrepancy over the course of just 1 month?

**Comment by mmontesanonyc** [comment]
Good question. 

As is the case throughout these data, summing one file won't add up to reported totals in another file - usually because it's common for there to be missing demographic information. In this case, the number of people tested (not the number of tests, but the number of people tested) by ZIP does not include test records without patient address information. 

Additionally, the information shown by four weeks is deduplicated by person so that if one person is tested more than once in that four week period they are only counted once (again - not the number of tests, but the number of people tested). In the overall file, if they are tested on more than one day, they are counted more than once.

@azx65535, the difference between cumulative files from different dates doesn't reflect data that necessarily _happened_ between those dates. For more information [this note on Report date versus date of event](https://github.com/nychealth/coronavirus-data#report-date-versus-date-of-event), or consult previous answers to issues in this repository.

**Comment by azx65535** [comment]
Thanks for the response and understand the data issues around missing demographic information + taking differences in cumulative data across different dates.  But the magnitude of these errors/issues (i.e., 60% of tests not having ZCTA data!) make it very difficult to understand zip-code level trends.

It would be very helpful if the city can provide real-time zipcode level trend data (in whatever format/data that is most reflective of reality) that residents can use to make their own decisions.

**Comment by cerveser** [comment]
Hi all,
@mmontesanonyc if we use data-by-modzcta.csv of 2020-11-19 minus the data-by-modzcta.csv of 2020-11-18 we should get the daily numbers per zip code is that correct? 
I also find a gap with these numbers and the last7days-by-modzcta.csv file. For example ZIPCODE 10001 has a COVID_CASE_COUNT of 42 for dates 11-11 through 11-17 using this method, but in last7days-by-modzcta.csv with daterange November 11-November 17 this number is 26. How do you explain this?
Another question: is in the data-by-modzcta.csv file the COVID_CASE_COUNT a person who is positive only counted once?

**Comment by mmontesanonyc** [comment]
@cerveser thanks for asking. This is incorrect. Doing that would result in tests _reported on_ that day, not tests _conducted on_ that day. 

So, the difference in values bewteen last7days-by-modzcta and differences in data-by-modzcta over that 7-day period is that data-by-modzcta will be including tests conducted _prior_ to that time period, that get _reported_ within that time period. This is why we routinely recommend against interpreting the difference in cumulative files as trend data. Our data are by date of event, not by date of report. For more on this [please see our documentation](https://github.com/nychealth/coronavirus-data#report-date-versus-date-of-event) or search these issues for "report date." 

For your other question - yes, somebody is only considered a case upon their first diagnosis. If they have subsequent positive tests, they are in the data as positive tests but not as new cases.
