### ISSUE TITLE
Preserve counts-per-date granularity by zipcode

### ISSUE THREAD

**Issue by seils** [nychealth/coronavirus-data#127]
The granularity of data posted by zip code doesn't allow us to calculate the % positive in the same way that the city/state is using the determine what level of restrictions to apply to a zip code.  Can you please publish the per-date counts by zip code?

**Comment by azx65535** [comment]
Agreed

**Comment by allomate1** [comment]
Agreed. It’s misleading.

**Comment by travisp** [comment]
@seils Can you explain more how you think the data should need to be presented in order to match the method that NY state is using? I think the data is there, although it requires shifting through git commits (by doing so you can calculate daily new cases and tests)

**Comment by jshenry11963** [comment]
I have tried endlessly unsubscribe to this list since June, without success, despite following instructions. Please help! 

James S. Henry, Esq.

Global Justice Fellow, Yale U. 
(https://globaljustice.yale.edu)

Board Member, AIUSA
https://www.amnestyusa.org/

Sr Fellow, Col. U. Center
On Sustainable Investment 
(http://ccsi.columbia.edu
Contrib Ed, American Interest
Poynter Prize (Yale) 
Edward R. Murrow Fellow (Fletcher)
Member, NY Bar (1979-)
Coop Att., ACLU/NYCLU
Sr Advisor, TJN

Managing Director
Sag Harbor Group (SHG Inc.)
(001)(516)721-1452
sagharbor.com 
strategy design + execution
PO Box 2668
Sag Harbor, New York 11963

**Comment by seils** [comment]
HI @travisp - the positive test result numbers are not preserved by date.  For example, if the sum is updated by 300 cases today, the data that is posted doesn't show how those 300 cases are distributed across the previous _N_ days (i.e. it could be 100 cases for 3 days ago, 34 cases from 2 days ago, etc.).

**Comment by EmilHafeez** [comment]
Hi, I am just following up here to inquire if there has been a solution or change to this process I am not able to detect: I am hoping to obtain case count per date by zipcode, year-to-date. 

eh2928@cumc.columbia.edu.

Thanks, 
Emil

**Comment by mmontesanonyc** [comment]
Closing this issue as the November update changed what we were providing.
