### ISSUE TITLE
Title: Cumulative COVID_Case_Count Data dropped in multiple days 

### ISSUE THREAD

**Issue by DataAnalyst2020** [nychealth/coronavirus-data#129]
COVID_Case_Count data dropped compared to the previous date on the specific zip codes on the following dates. I’d like to verify if there was some cleaning or data validation done that adjusted this value. And what caused this value to change. 

11204  8/25
11218  8/21, 9/8, 9/10, 9/11, 9/22
11219  9/11, 9/12, 9/17, 9/19, 9/20

Also, Total_COVID_Tests data dropped in Brooklyn on 8/18 compared to 8/17. Please verify this issue as well.

Thanks.

**Comment by mmontesanonyc** [comment]
Yes, this is a result of standard data cleaning procedures and occurs routinely. This can be caused by, for example, updated address information for a patient showing they live outside of NYC and so should be removed from our count. Some more information is available in [previous issues](https://github.com/nychealth/coronavirus-data/issues?q=%22data+cleaning%22).
