### ISSUE TITLE
State and City Case and Testing Data

### ISSUE THREAD

**Issue by HarryLeroy** [nychealth/coronavirus-data#138]
The gap between the state's and city's case and testing data has been noticeable in the past month. In the month of October (26 days of reporting so far), the state has reported 15,136 new positives across the five boroughs, whereas the city has reported 13,531 new cases and 17,030 new positives. The number of tests also differs, with the state having reported 1,196,010 new tests and the city only 1,019,040. These are both based on date of announcement as opposed to date of testing (only the city differentiates between the two), so timing should not be the main issue here.

What accounts for the differences between the state's and city's data?

Thanks,
Harry

**Comment by mmontesanonyc** [comment]
Thanks for the inquiry.

Generally, the City and the State will almost never have the same numbers for the same metrics, though they report the same general trends. The reasons for this include: different data sources for different metrics, different analytical and informatics processes, and different uses of event date or report date.

Also, it's important to note that we don't report the number of tests - we report _number of people tested_. So, for example, tests.csv shows daily counts of number of people tested, by test date. If a person gets tested twice in one day, they're counted once. In files that report weekly or monthly data, they are deduplicated by that timeframe, so that one person getting multiple tests is only counted once.

**Comment by yydl** [comment]
@mmontesanonyc Out of curiosity, what are the unique identifiers used to determine if someone is a duplicate?
