### ISSUE TITLE
Difference between Test Counts in Latest v. Total

### ISSUE THREAD

**Issue by BillyMadison2018** [nychealth/coronavirus-data#152]
Thanks again for this resource - I have noticed that for the zip code i monitor (11372), the recent number of tests in the Total dataset is much much lower than the Latest dataset.  Using the same date range used in Latest, the Total set comes back with 842 tests, while the Latest dataset says that there were 1897 during that timeframe.  

Can you let us know where these extra tests are coming from?

**Comment by mmontesanonyc** [comment]
Hi there, thanks for the question.

Taking the difference between two dates of cumulative files results in data that were _reported_ during that time period, not tests that were _conducted_ during that time period. So, in short, this means that the "extra tests" are coming from dates before your time period of interest. [Our Readme](https://github.com/nychealth/coronavirus-data#report-date-versus-date-of-event) and some other issues logged in this repo discuss the difference between report date and event date, and we caution against interpreting the difference in dated cumulative files as data from that time period.

Additionally, because our data use event date and not report date, recent data, such as those found in latest, may be subject to underreporting. We provide [data at a 3-day lag](https://github.com/nychealth/coronavirus-data#reporting-lag), and backfill data into prior dates as more data are reported to us.
