### ISSUE TITLE
7 Day Average

### ISSUE THREAD

**Issue by davor999** [nychealth/coronavirus-data#153]
Can you explain how the 7 day average is calculated? It doesnt seem to match with the last 7 days in fact? 

For example  looking at the case data today. The  average of the last 7 days calculated manually is 2.9%. But in the table the 7 day average shows as 2.57%. 

It seems there is some some of lag in the 7 day average?  Can you explain please?

**Comment by dyoung95437** [comment]
davor999 : Did you get an answer on this or figure it out? I see you yourself closed the issue. I am also going to post a new issue. I am wondering same thing and about the "PERCENT_POSITIVE_7DAYS_AVG" for the file coronavirus-data/latest/now-tests.csv, which does not match the actual 7 day average from the daily "PERCENT_POSITIVE" column when I calculate it myself. This now has immediate impacts too, since the Mayor says he will close all schools when this data shows 3% 7-day-average positivity but when I calculate it based on the daily data here the city reached that threshold back on 11/9 and has been above it ever since. The same issue is evident with the data at the city's "Milestones" page, which matches the "now-tests.csv" percentages, at this link: https://www1.nyc.gov/site/doh/covid/covid-19-goals.page

**Comment by davor999** [comment]
I figured it out. You need to add up the cumulative cases and positives for the past week  (then weekly cases / weekly tests = average rate)

There are a much lower number of tests done on the weekend, which also seem to yield consistently higher positives tests. 
That's why simply averaging the 7 day positive rates gives a number that is too high.
