### ISSUE TITLE
Latest files lagging 3 days behind

### ISSUE THREAD

**Issue by jakedobkin** [nychealth/coronavirus-data#154]
Hi-

I've noticed the files in the Latest directory are 3 days behind (ie. they're updated to 11/10 today 11/13).  You can see it for instance on this one: https://github.com/nychealth/coronavirus-data/blob/master/latest/pp-by-modzcta.csv

Would it be possible to include these three days, even if they're incomplete (we could mark them incomplete on our charts, but at least we'd be closer to current).  

Thanks,

Jake

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. 
As written in [our documentation](https://github.com/nychealth/coronavirus-data#reporting-lag), all data are published at a 3-day lag. This is to ensure that when we publish data, it's meaningful. Previous dates do get backfilled as more data come in, but it's simply unreliable to publish data that is so incomplete that it risks being misleading. A 3-day lag balances timeliness with completeness and meaning.

**Comment by jakedobkin** [comment]
The issue is that on the milestones page, you have another day- https://www1.nyc.gov/site/doh/covid/covid-19-goals.page - for instance, today you have the milestones graph up to the 12th, but here the data only goes to the 11th: https://github.com/nychealth/coronavirus-data/blob/master/latest/pp-by-modzcta.csv - can you just give us the file that you're basing the milestones graph on, so we can include it in our reporting?  Right now, the reporters are mad because our updating charts are a day behind the milestone chart you're publishing, you know?

Thanks,

Jake

**Comment by seeess1** [comment]
When did the 3-day lag start? I've been working with this data for months and it didn't use to have a 3-day lag. It was typically up-to-date through the previous day. I'm primarily working with data-by-day.csv, by the way.

**Comment by mmontesanonyc** [comment]
@seeess1 
Our update on 11/9 brought the data in data-by-day.csv into alignment with other reporting at a 3-day lag. Since you've working with those data for a while, you're likely aware that prior to the lag, the most recent days had artificially small counts that got revised upward significantly. To shed more light on this, you might be interested in [our data on test result turnaround time](https://github.com/nychealth/coronavirus-data/tree/master/trends#testing-turnaroundcsv).
