### ISSUE TITLE
In now-tests.csv, "PERCENT_POSITIVE" and "PERCENT_POSITIVE_7DAYS_AVG" don't appear to match

### ISSUE THREAD

**Issue by dyoung95437** [nychealth/coronavirus-data#155]
Let me just start by thanking you all very, very much for the recent website upgrade: it is really wonderful. Now to the issue: for the file coronavirus-data/latest/now-tests.csv, how are the values in "PERCENT_POSITIVE_7DAYS_AVG" calculated? They do not match what I get when I calculate the 7 day average from the daily "PERCENT_POSITIVE" column. The values in the "PERCENT_POSITIVE_7DAYS_AVG" appear to be consistently lower. The same problem is evident at the city's "Milestones" page which appears to present the same numbers from those columns here: https://www1.nyc.gov/site/doh/covid/covid-19-goals.page. Also the Mayor is citing these same positivity numbers and using them for the basis for whether to close the schools or not based on whether the 7-day average has reached 3%. However when I calculate the 7-day-average with the daily % positive from both the "Milestones" site and the "PERCENT_POSITIVE" column in the file coronavirus-data/latest/now-tests.csv, it appears the city already exceeded that 3% threshold back on 11/9. A lot of people in the city are very concerned about this discrepancy, there has been a lot of talk about on Twitter for example, so please, please clear up how this was calculated and why there is this discrepancy. Thank you so much for all your hard work on this and esp. thank you again for the new website format, esp. all the granular detail for positivity rates by zipcode!

**Comment by jimmykaiser** [comment]
Just want to add that I am seeing a similar issue in `totals/data-by-modzcta.csv`. `COVID_CASE_COUNT` divided by `TOTAL_COVID_TESTS` does not equal `PERCENT_POSITIVE`. For example, in the 11/13 commit, zip code 10001 has 511 cases and 11,183 tests, resulting in a percent positive rate of 4.57%. But the `PERCENT_POSITIVE` value is 4.04. The percent positive rates by zip code I am calculating appear to be consistently higher.

**Comment by mmontesanonyc** [comment]
Thanks for the question.
@dyoung95437: PERCENT_POSITIVE_7DAYS_AVG isn’t calculated as the average of percent positive _values_, but rather, the average of people positive divided by the average of people tested - as indicated in the [documentation](https://github.com/nychealth/coronavirus-data/tree/master/trends#testscsv).

In other words: If I have 4 out of 5 things (80%), and 6 out of 10 things (60%), my average isn’t  (60+80)/2 = 70. Rather, it’s (4+6)/15 = 11/15 = 73%. This matters for testing because often, weekend days see much lower testing volumes and higher percent positivity. It’s important to weight those days (and all days) by test volume, and not just do strict averaging of percent positive values. 

@jimmykaiser, [our documentation](https://github.com/nychealth/coronavirus-data/tree/master/totals#data-by-modzctacsv) may be helpful for understanding those fields. Percent positive is not "cases/tests," since a person may test positive multiple times, but is only counted as a case upon first positive test.

**Comment by jimmykaiser** [comment]
Thanks @mmontesanonyc! That makes sense to me. Is that a change in business rules? Prior to the 11/9 update, with the same documentation, cases/tests = percent positive in the data-by-modzcta file.

**Comment by mmontesanonyc** [comment]
@jimmykaiser apologies for the confusion, I was still thinking of the file mentioned in the original issue. To answer your question about data-by-modzcta more thoroughly: Cases and tests come from two different data systems, so there are a few reasons why case counts and unique people who test positive sometimes differ in this file. These include getting positive case reports without getting corresponding positive lab reports, or instances where case data has a different address for a single patient than lab data. These are all ordinary realities of public health surveillance data, particularly when we have a constant influx of new data. We do extensive, ongoing data cleaning to ensure that even when these fields aren't identical, they're still reliable and reflect the overall trends, which is what we should keep our eyes on.

**Comment by jimmykaiser** [comment]
@mmontesanonyc The file doesn't contain different columns for case counts and unique people who test positive. It just has a column "COVID_CASE_COUNT". Is that column showing case counts (since it is not the numerator for "PERCENT_POSITIVE") and the count of unique positive people (the actual numerator) is not included in the file?
