### ISSUE TITLE
New tests 11/18 

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#157]
Calculating the number of new tests for one day (11/18 vs 11/17), the numbers are in some cases half what they have been. Doesn't make sense with long testing lines, so it there something wrong with these test counts?   

New Tests 
  | Lincoln Square |   | Upper East   Side/Yorkville |   | East Harlem
Zip | 10023 | 10069 |   | 10028 | 10128 |   | 10029
16-Nov | 148 | 22 |   | 81 | 153 |   | 137
17-Nov | 132 | 18 |   | 114 | 164 |   | 164
18-Nov | 66 | 16 |   | 52 | 65 |   | 89

![image](https://user-images.githubusercontent.com/66915393/99597980-d7758a00-29c6-11eb-9ccb-ba26950657b7.png)

**Comment by mmontesanonyc** [comment]
[It takes time](https://github.com/nychealth/coronav) for information on the tests conducted at the end of those long lines to get to the Health Department. 

Per [our documentation](https://github.com/nychealth/coronavirus-data/tree/master/totals), taking a cumulative file and subtracting one day's values from the next does not result in the number of new events for one day. It results in the number of tests reported, not conducted. See more about [Event Date versus Report Date here](https://github.com/nychealth/coronavirus-data#report-date-versus-date-of-event) and in many other issues - we discourage treating the daily difference in cumulative files as trend data, since it reflects when we learned things but — crucially, for your question — **not when those things happened**.
