### ISSUE TITLE
Test counts

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#159]
The # of tests by Zip seems really really low given the insane lines at City MD - people waiting up to 9 hours for tests. I re-read that Test count is PCR test, not rapid test. That might explain what's happening if most people are getting rapid testing. But then how are those tests counted in your data?? And does that mean your positive cases are only from PCR and does not include rapid tests either?

**Comment by jpfreeley** [comment]
Some background on PCR vs Rapid: https://www.nytimes.com/2020/11/22/nyregion/Coronavirus-cases-numbers-nyc.html

**Comment by svfnyc** [comment]
Thank you for sharing the article - I knew there was an issue but didn't have all the details. I know what I'm analyzing is more directional just to understand how safe my immediate neighborhood is, but just doesn't jive with what I'm seeing in real life. I also wonder how many of these people in line live outside the city (college students, traveling family) who don't live in this zip code and so maybe wouldn't be attributed to my zip?

**Comment by mmontesanonyc** [comment]
[Per our documentation](https://github.com/nychealth/coronavirus-data#reportable-disease-surveillance), currently, the data in this repository are for PCR tests only, and confirmed cases are people who have tested positive by a PCR test.

**Comment by jpfreeley** [comment]
I think that what we have to also understand is that except for the rush to "test before Turkey", and although there is "test often" messaging out there, generally speaking, most persons feeling in good health are not interrupting their lives to go seek a test. It's difficult enough to get people to mask up (or vote), let alone spend time and energy to test. And for that reason, I believe, the numbers are generally higher than if all the healthy feeling people got off their tucki (tuckuses?) to go stand in "the cold" to get a test that they believe will tell them what they already (think they) know. Case in point, me and just about everyone I know. One thought that I had was to bring the tests to where the lines are developing organically, like outside every Trader Joe's location. 

I believe that most of the people who "test" have some underlying reason to suspect exposure (perhaps they were called by a tracer or alerted by the app or had a child in a school with a case) or are they planning a potential future "visit". I truly believe that if all the actual healthy people decided to go and get tested, we'd see far lower positivity rates. 

Lastly, I believe that's exactly what happened here, healthy people made the mad rush to test before travel or expected plans with loved ones. But we will need to check this same chart again in 1 week due to back-filled data. Afterall, nothing is as it seems "today"...we need to wait a few days to see what the true story with "yesterday" was hence the 7-day average. 
https://public.tableau.com/profile/integrated.data.team#!/vizhome/COVID-19UpdatedPublicHealthMilestones/TestinginNYC

**Comment by jpfreeley** [comment]
> [Per our documentation](https://github.com/nychealth/coronavirus-data#reportable-disease-surveillance), currently, the data in this repository are for PCR tests only, and confirmed cases are people who have tested positive by a PCR test.

The documentation is confusing due to the conflicting info at this link https://github.com/nychealth/coronavirus-data#antibody-testing  quotes below: 

> "This repository contains data on antibody tests" and 

> "For calculations of the number and percentage of people with positive results, people are considered positive if they ever receive a **positive antibody result**, regardless of whether they have received negative results as well."

Juxtaposed above this quoted section is this link: https://github.com/nychealth/coronavirus-data#reportable-disease-surveillance which contains this line: 

> "The laboratory criteria for reporting a person with confirmed COVID-19 infection (“case”) are based on the PCR test, and as such, all of the confirmed COVID-19 cases reported out by the Health Department represent people with **positive PCR tests.**"

So which is it? PCR = Positive or Serology = Positive .. clearly the documentation above suggests that both are true.

**Comment by mmontesanonyc** [comment]
Good catch, thanks for being thorough - I've edited my comment. Data labeled as being for antibody testing are for serology/antibody testing. All confirmed case, hospitalizations, and death data are for people who have tested positive with a PCR test.

**Comment by jpfreeley** [comment]
> Good catch, thanks for being thorough - I've edited my comment. Data labeled as being for antibody testing are for serology/antibody testing. All confirmed case, hospitalizations, and death data are for people who have tested positive with a PCR test.

I think that the clarity regarding "PCR only" found in the data-definition of this file (https://github.com/nychealth/coronavirus-data/tree/master/totals#data-by-modzctacsv) needs to be explicitly replicated to the definitions of the other files. Perhaps even with the veribiage that this "excludes antibody tests". And likewise, for consistancy, the antiboday data definitions may want to explictly exclude PCR.
