### ISSUE TITLE
12/7 update question

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#164]
A couple of questions about today's update (12/7). First, it was uploaded very early (my estimate around 7 am) vs the usual 1pm. Second, for the zips I follow, there seems to be a major downward adjustment to the number of cases and deaths. I know you hate when I use your data for daily tracking, but this combination just seems very odd and I'm curious if some data has been missed in the early morning upload and/or will there be an updated upload this afternoon. Thanks.

**Comment by mmontesanonyc** [comment]
Hello, thanks for asking. [Per documentation](https://github.com/nychealth/coronavirus-data#important-changes-on-december-7-2020), the 12/7 update reflect a revised geocoding process that may change some data for the ZIPs you track. Secondly, all of our data are published at a 3-day lag, so the fact that we updated in the morning instead of the afternoon doesn't affect what data are included in that update.
