### ISSUE TITLE
data-by-day.csv last updated on 12/12

### ISSUE THREAD

**Issue by joearedmond** [nychealth/coronavirus-data#169]
Hi NYC Health,

My hospital is relying on this data -- thank you for posting it here!

I noticed the last date for which we have data in data-by-day.csv file is 12-12-2020. Does this get updated daily? Why would this data be missing? I'd love to get access to 12-13 though today!

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. Glad that your hospital finds these data helpful. 

We publish data by [date of event](https://github.com/nychealth/coronavirus-data#report-date-versus-date-of-event) (when it happened) instead of report date (the date the Health Department found out about it). Cases diagnosed based on a test that was in the past couple of days may not have been reported to the Health Department. So, all data in this repository is [published at a 3-day lag](https://github.com/nychealth/coronavirus-data#reporting-lag) to ensure that data are more complete, and data are also backfilled with subsequent updates as more tests are reported.

**Comment by joearedmond** [comment]
Thank you!
