### ISSUE TITLE
Is there historical/archived data available? 

### ISSUE THREAD

**Issue by lauraktravis** [nychealth/coronavirus-data#172]
Is there a directory or file with historical data on weekly positive test rates by borough/zip code/city or daily cases per 100k by zip code?

We have been pulling and saving the data from the files `data-by-modzcta.csv`, `data-by-day.csv`, and `pp-by-modzcta.csv` since September, but are missing data prior to this. Thank you!

**Comment by xrisfg** [comment]
There is an `archive/` folder. Does that have what you're looking for?

Because it's GitHub, all history is preserved. You can look at the [commit history](https://github.com/nychealth/coronavirus-data/commits/master?after=f75e7410a4f4c3b03bb6d9e381fa6312f95e3d41+139&branch=master) - from September and earlier, in this link - as a kind of "time machine" to get earlier copies of the current files.

However, all the measures have changed over the course of the epidemic. There may not be continuous history going back as far as you want. This is especially true if you're trying to narrow the scope, e.g.: by zip code. Those figures were simply not available during the first few months of the epidemic.

**Comment by xrisfg** [comment]
Also, if you're just picking up the latest data, check out the `[trends/](https://github.com/nychealth/coronavirus-data/tree/master/trends)` folder. That has data going back to March in most cases, by Borough, and by Zip Code for some.

**Comment by mmontesanonyc** [comment]
Weekly positivity is available in [trends/percentpositive-by-modzcta](https://github.com/nychealth/coronavirus-data/blob/master/trends/percentpositive-by-modzcta.csv).
