### ISSUE TITLE
percentpositive != caserate / testrate

### ISSUE THREAD

**Issue by tonetto** [nychealth/coronavirus-data#184]
Hi, in my understanding, the weekly `percent positive` (**P**) should (at least nearly) match the ratio of `case rate` (**C**) and `test rate` (**T**), but it's never the case. In either city, borough, or ZCTA, `P > C/T` is always the case.

You define in your documentation:

- `percent positive := number of positive tests / number of all tests`
- `case rate := number of positive tests / 100 000`
- `test rate := number of all tests / 100 000`

So, just sounded intuitive that I could verify the percent positive, but those don't match. Sorry if I am missing something obvious here, and thanks so much for publicly sharing these data!

**Comment by tonetto** [comment]
Here's an example, showing these numbers for the entire city of NY:

![image](https://user-images.githubusercontent.com/1403006/111168514-6c1d7c80-85a2-11eb-9372-d2a9a70c84cf.png)

**Comment by mmontesanonyc** [comment]
Hello, thanks for the question. 

The reason that percent positive doesn't match case rate / test rate is because the case rate is not the number of positive tests / 100,000. A person may test positive several times _but is only diagnosed as a case once_ - upon the first positive test. 

Additionally, your definitions/interpretations are off - percent positive is the percent of _people tested_ who test positive, not the number of positive tests divided by the number of total tests. Similarly, case rate and test rate are the number of _people diagnosed_ and _people tested_, respectively, per 100,000. That is, all of these metrics are deduplicated by person for the unit of time reported.
