### ISSUE TITLE
Massive drop off in case reporting, increase in positivity

### ISSUE THREAD

**Issue by dd11235** [nychealth/coronavirus-data#186]
Hi, I'm wondering what has happened to account for the drop off in reported total tests in last few days, esp. for 3/17 where I see a total of only 1,362 tests (as of 3/20 data release), and the massive surge in positivity which I assume is a result of this severely incomplete data -- with 51.98% positivity for 3/17 (as of 3/20 data release)? This is visible in the graphs on the site for testing and the Github data, and appears unusual. Is there some kind of major clog in the testing data pipeline here and what is it? I'm just very curious. Thank you for all you do!

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. As mentioned in [the commit note on recent days](https://github.com/nychealth/coronavirus-data/commit/333f451e429d85afe62c909f6d2c6186040074d1) and [the note on the webpage](https://www1.nyc.gov/site/doh/covid/covid-19-data.page), there have been delays in receiving data from New York State this past week. This has resulted in initial reports of very low test and case counts for recent dates. These dates will be backfilled once the issue is fixed.
