### ISSUE TITLE
Time series data by MZCTA

### ISSUE THREAD

**Issue by phanidevarakonda** [nychealth/coronavirus-data#191]
Hi. Where can I get all data from the start of COVID-19 till the latest date by MZCTA? There is a "COVID-19 daily cases of hospitalizations and deaths.csv". How can I get something similar for MZCTA? 
Thanks!

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. We don’t publish those data (by both modzcta and date) because of the risks of violating patient confidentiality with data of that high resolution. However, we do provide test rate, percent positive, case rate by modzcta and week going back to August 2020, and hospitalization, and death rate by modzcta and month going back to March 2020, in the Trends folder.

**Comment by phanidevarakonda** [comment]
Thanks mam

Phani Devarakonda
