### ISSUE TITLE
Method for Creating the MODZCTAs

### ISSUE THREAD

**Issue by DaveOTDA** [nychealth/coronavirus-data#194]
The documentation gives a general reason (stable population estimates, zips v. areas) for creating and the MODZCTAs, and provides crosswalks, but not the precise method used to create them.  Is that available?  Otherwise it is hard to assess their utility beyond a broader population base.  Also, has there been a validation test to see if rate estimates are better when using numerators constructed from address zips mapped to ZCTAs versus MODZCTAs.

**Comment by mmontesanonyc** [comment]
Thanks for the question. 

ZCTAS (ZIP Code Tabulation Areas) are created by the US Census Bureau. Modified ZCTAS (modzctas) are created by combining certain low-population ZCTAs with a neighboring ZCTA. That is: some modzctas are made up of one ZCTA. Some are made up of several ZCTAs. A case is assigned to a modzcta when the patient's address of residence is geocoded, assigned to a census block, and then assigned to the ZCTA that contains that census block. It's then assigned to the modzcta that contains that ZCTA. This might either be a modzcta that is identical to a single ZCTA, or a modzcta that is made up of more than one ZCTA.

In epidemiology is common to seek larger denominators (either by looking at data over a larger area, or over a larger time period) to stabilize rates, otherwise small changes in counts might lead to dramatic changes in rates.

**Comment by DaveOTDA** [comment]
Thanks for the response, that clarifies that the outcome of the approach still falls along the ZCTA boundaries, albeit combined, as opposed to something like ZCTAs joined with contiguous census blocks.  However, my question was also about how you chose which ZCTAs to combine (e.g., minimum population quotas, how to choose which contiguous - assuming they are contiguous - ZCTA to use).  Any systematic documentation on that?  Thanks again!
