### ISSUE TITLE
Poverty Level vs Death Rate using ACS Data

### ISSUE THREAD

**Issue by TrivialBits** [nychealth/coronavirus-data#197]
I would like to know which table/column in ACS was used to assign the poverty level to a particular zip code. Was it the column with heading (S1701_C03_001E: Estimate!!Percent below poverty level!!Population for whom poverty status is determined) or was there another method? Essentially, is this column the same as FPT?

I'm using death rate for each zip code from the 'totals' folder in github and combining it with ACS data by zip code. Then using the column: S1701_C03_001E to create 4 poverty categories (Low, Medium, High, Very High). I'm not getting the same average death rates by poverty level.

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question.

From your description, it sounds like you are calculating crude rates. Our case, hospitalization, and death rates by neighborhood poverty level are [age-adjusted](https://github.com/nychealth/coronavirus-data#rates-per-100000-people). Age adjustment weights data so that areas with different age distributions can be compared. If you are calculating crude rates, you won’t get the same values, and it's not possible to replicate our calculations of age-adjusted rates with the data in this repository. 

To answer your question about ACS data: to calculate poverty, we used B17001_002E for the numerator and B17001_001E for the denominator. We used 2014-2018 ACS data; if you’re using a different year, or different [category cut points](https://github.com/nychealth/coronavirus-data#poverty-groups), you might not get the same poverty estimates.
