### ISSUE TITLE
Miscounting vaccinated & unvaccinated cases

### ISSUE THREAD

**Issue by martinssanchez** [nychealth/coronavirus-data#231]
Your recent data (below) contradicts CDC's findings regarding vaccine efficacy waning. Instead of seeing waning VE like all other countries, your data implies VE is growing exponentially. People may be misled into thinking that they are more protected than ever and delaying their boosters.

I understand it's hard to achieve 100% accuracy, but your data seems to directly contradict what we're seeing from the CDC and other countries like UK, Israel, and Denmark.

As a suggestion, try breaking a separate category called "vaccination status unknown". It'd be good to keep track of how many cases were in this category too. Thanks!

![image](https://user-images.githubusercontent.com/98244659/150662260-a9fd7d44-68cc-4a79-a51e-7aa8522405fc.png)

**Comment by warrtalon** [comment]
Agree. This is a reflection of the vaccine records not being matched yet (and being impossible to match them all anyway). When everything defaults to unvaxxed, it skews the rates by increasing the Unvax numerator and decreasing the Vax numerator along with the Unvax denominator already being far too low due to using the July 2019 census estimates (about 500k lower than the 2020 census).

Large, verified accounts on Twitter (and likely on other platforms) are sharing these charts as if VE suddenly skyrocketed against Omicron when the opposite is true in every other country. This could be more damaging to vaccination efforts than showing only data through 12/25.

**Comment by mmontesanonyc** [comment]
[Our documentation on how we count these cases, hospitalizations, and deaths, is here](https://github.com/nychealth/coronavirus-data/tree/master/latest#readme). Communicable diseases move differently though different populations based on the patterns of the many, many factors in addition to vaccination status that can affect transmission and disease severity. Patterns in NYC are consistent with those seen in other areas: that case rates are dramatically higher among unvaccinated people.

**Comment by warrtalon** [comment]
> [Our documentation on how we count these cases, hospitalizations, and deaths, is here](https://github.com/nychealth/coronavirus-data/tree/master/latest#readme). Communicable diseases move differently though different populations based on the patterns of the many, many factors in addition to vaccination status that can affect transmission and disease severity. Patterns in NYC are consistent with those seen in other areas: that case rates are dramatically higher among unvaccinated people.

Hi, this is not true. Case rates are not dramatically higher among unvaccinated people. In the UK, case rates are dramatically higher among the vaccinated, including those with 3 doses, in all age groups except 0-17. Similar is noted in Scotland, Denmark, and Israel.

The UK has a good handle on its population denominators while NYC is using 2019 intercensal, which undercounts the Unvaxxed population by 500,000 or more.

UKHSA source: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1054071/vaccine-surveillance-report-week-6.pdf

UKHSA chart: 
![image](https://user-images.githubusercontent.com/98188224/154114961-4cc47dd9-4f1e-49c3-b289-11004a93b0e6.png)


Even in the NYC data, the week of 12/18 has reached 63% vaccinated - after another 8,000 cases were record-matched in last week's update. Using 2020 census for Unvax puts that at 1.88:1 (Vax-to-Unvax). This means we're close to seeing the proper rates with Omicron but not all the way there yet.
![image](https://user-images.githubusercontent.com/98188224/154115682-ba169b65-7e1b-4f86-8e11-b40aa7201fec.png)

**Comment by skyl** [comment]
Status unknown should not be counted as unvaccinated. It's very misleading. 

Scotland provides a good sanity check, since they have much better records for who is vaxd and who is not.

![Screenshot_20220218-182207_Drive](https://user-images.githubusercontent.com/61438/154783507-fa0f456f-87a4-4ae6-afe9-28fcc887c3fc.jpg)

![Screenshot_20220218-182314_Drive](https://user-images.githubusercontent.com/61438/154783516-162b4d0b-e70b-4b7a-b7f1-2c4de0883c8a.jpg)

![Screenshot_20220218-182409_Drive](https://user-images.githubusercontent.com/61438/154783533-4a8875f5-5589-4e59-8302-92b055ad524f.jpg)

The NYC numbers do not appear sane or realistic.
