### ISSUE TITLE
Why are case rates among boosted folks higher than unboosted ones?

### ISSUE THREAD

**Issue by penguinland** [nychealth/coronavirus-data#245]
I was looking at https://github.com/nychealth/coronavirus-data/blob/master/latest/now-weekly-breakthrough.csv .

For death rates and hospitalization rates, the unvaccinated had a higher rate than the vaccinated-but-not-boosted, who in turn had a higher rate than the vaccinated-and-boosted. However, for the case rates, the vaccinated-but-not-boosted are _lower_ than the boosted folks, which surprises me. Any chance those two columns are accidentally swapped?

Thanks for all you do, and keep up the good work!

**Comment by mmontesanonyc** [comment]
Hi, thanks for your inquiry. These columns aren't swapped. The fact that boosted populations have higher case rates may reflect differences in populations, exposure, and behaviors, rather than the effectiveness of the booster - since, as you point out, hospitalization and death rates are lower for boosted populations. 

Additionally, the higher average weekly case rates in now-breakthrough-summary.csv, too, reflect populations existing in different time periods - since people only started receiving boosters in Fall 2021, the rate for those vaccinated and boosted only really covers the fourth COVID wave (when Omicron lead to extremely high case rates), whereas the rate for those vaccinated and not boosted covers a longer time period, including waves with much lower peak case rates.

**Comment by penguinland** [comment]
Thanks for checking! I think you're onto something with the differences in population behaviors: a friend of mine noted that people who are unboosted might be less likely to self-report a positive at-home test, which would explain everything. 

Again, keep up the good work!
