### ISSUE TITLE
Revised Historical Data by Zipcode

### ISSUE THREAD

**Issue by lazyazn6** [nychealth/coronavirus-data#52]
Hi,

I was wondering if there is a repository with revised daily data for each zip code.  Since there is a delay in reporting, the past files have stales numbers.  

I am trying to plot the trend of new cases for each individual zip codes.   

Thanks

**Comment by xrisfg** [comment]
lazyazn6: You can get the past edition of any of the files by clicking History at the top of the file, and selecting the date you want by clicking the <> symbol for that revision/date. That puts you in the past version of the entire repository, like a time machine.

**Comment by lazyazn6** [comment]
Thanks @xrisfg.  

Due to the delay in reporting, the past versions of the cases by zipcode file have stale numbers for the dates that they reported.  I was wondering if i can find a file with revised numbers that account for the delay in reporting.

**Comment by xrisfg** [comment]
Not sure what you're looking for. The latest version of the file has the most current numbers.

If you want to see how much the numbers changed over time, you can compare the current and a past version to see how much they've changed. tests-by-zcta.csv has been updated most days since April 1:
https://github.com/nychealth/coronavirus-data/commits/master/tests-by-zcta.csv

I've done that myself for probable-confirmed-dod, which only has a week of history.

[NYCHealth - probable-confirmed-dod.pdf](https://github.com/nychealth/coronavirus-data/files/4532317/NYCHealth.-.probable-confirmed-dod.pdf)
