### ISSUE TITLE
Large increase in recent testing data?

### ISSUE THREAD

**Issue by pigsandpineapples** [nychealth/coronavirus-data#56]
Looking at the tests-by-zcta.csv data it seems (for some zipcodes at least) like there has been a significant increase in the number of tests and cases between 4/25 and 4/26. For the previous 14 days, number of new tests per day and number of new cases per day had been increasing at a pretty much steady linear pace in certain zipcodes (I am only focusing on some, not all of the zipcodes in the file). Do you know if that is because of some reporting truing-up of tests and resultsfrom the past, or whether it reflects an increase in testing by the city or maybe there is some other explanation? Thanks!

**Comment by igordot** [comment]
The numbers are lower for 4/27, so maybe there was some reporting error.

**Comment by johnurbanik** [comment]
Hoping this is the case, but I'm not sure what the reporting error would have been - the increases between 4/25-4/26 have very high covariance, but there are some ZCTAS that don't change as much.

Excuse the poor color palette, but I just scraped the git history and threw this together for a bit more visual exploration.

![chart](https://i.imgur.com/D3PTaxZ.png)

**Comment by johnurbanik** [comment]
@mmontesanonyc any chance we can get an explanation of what happened with regard to the reporting error?

**Comment by mmontesanonyc** [comment]
There was a data issue affecting counts for that day, which we have resolved. Please note, data are always preliminary and subject to change.

**Comment by johnurbanik** [comment]
Thank you for the clarification.

Can we get any clarification as to what the issue was? The process that generated the erroneous data is important to understand. 

Given that NYS and NYC report different data and that there is and has been a discrepancy between the zip code aggregated counts and the reported borough level counts, I'd like to know what the best source of truth is.

An explanation of what type of issue effected counts on 3/26 would provide some confidence that the data represented is accurate (to our best present knowledge). The issue does not seem to be a simple data entry error (like double adding the new counts to the cumulative counts, some fixed offset being added to all counts) or one following some easily discoverable statistical process, and is widespread across all zipcodes.

If you're able to disclose what happened, please do.

**Comment by mmontesanonyc** [comment]
It was just a one-time data issue that we resolved. As always, data posted are preliminary and subject to change. We recommend against compiling data by report date as you have done as it is prone to misinterpretation. The data we report out each day is not reflective of the number of tests conducted on the previous day.

To address your point about the discrepancy between ZIP aggregated counts and reported borough-level counts: this is expected. Summing counts may not match reported aggregates because of records with missing geographic information: we may have records where we have a patient's borough but not their full address and ZIP code, or ZIP but not borough (some ZIPs cross borough boundaries). This is the case for breakdowns by any subpopulation.

**Comment by pigsandpineapples** [comment]
@mmontesanonyc I do appreciate whatever data is made available here, and I don't mean to beat a dead horse, but can you explain a bit more what you mean that the "data we report out each day is not reflective of the number of tests conducted on the previous day"?

For example, the file uploaded on April 29 showed that there had been 1673 tests done on patients who reside in zip code 10016 and that 573 of those tests came back positive. The file uploaded on April 30 showed for the same zip code that there had been 1723 tests done and 582 of those came back positive.

Are you saying that basically those 50 extra tests and 9 extra positive results may not necessarily all be from the 29th, that some of them could be from the 28th or 27th or something that just hadn't been reported until now?

Also, in a related question, do we know whether these tests and positive results are for unique individuals? Or is it possible that an individual would have been tested twice and that would increase the completed test (and possibly positive test) count by 2?

Thanks!

**Comment by mmontesanonyc** [comment]
Due to reporting lags common to surveillance, some tests reported yesterday may have been conducted several days ago but only recently reported. For this reason, for daily data (e.g., cases, hospitalizations, and death counts by day) we use date of occurrence, not date of report. This better reflects when things are happening - rather than when they're getting reported. 

Data on tests administered are unique individuals on unique days. So yes an individual who is tested on two different days is reflected twice in the denominator.
