### ISSUE TITLE
Spike on April 26th?

### ISSUE THREAD

**Issue by natalieoshea** [nychealth/coronavirus-data#61]
There is a large spike in the number of cases and tests on April 26th in every zip code that immediately drops back to the normal rate of increase the following day... Is this a data reporting error?

**Comment by ParamjitGill** [comment]
This was pointed out earlier in Issue #54.
April 26 zipcode counts seem to be incorrect on the higher side. For example, for zipcode 10001, we have, total tested by April 26 as 851 and April 27 update shows the total tested as 737 which is less than 851. Remember the counts are cumulative.

**Comment by natalieoshea** [comment]
Are there any plans to fix this in the data?

**Comment by mmontesanonyc** [comment]
This was addressed in [Issue #56 ](https://github.com/nychealth/coronavirus-data/issues/56). The data were fixed with the subsequent upload on the 27th.

**Comment by natalieoshea** [comment]
That doesn't really help with wanting to analyze historical trends though... are there reliable data for the number of tests/cases specifically on the 26th?  If not, then I'll just drop all data from that date. I know this has been addressed in other issues, but appending the data rather than replacing the entire csv would be helpful for researchers interested in historical trends.

**Comment by mmontesanonyc** [comment]
This data file shows cumulative data, not trend data. We recommend against compiling data by report date, as it is prone to misinterpretation. The data we report out each day is not reflective of the number of tests conducted on the previous day. 

Due to reporting lags common to surveillance, some tests reported yesterday may have been conducted several days ago but only recently reported. For this reason, for daily data (e.g., cases, hospitalizations, and death counts by day) we use date of occurrence, not date of report. This better reflects when things are happening - rather than when they're getting reported.
