### ISSUE TITLE
ZCTA vs MODZCTA

### ISSUE THREAD

**Issue by igordot** [nychealth/coronavirus-data#64]
I noticed you recently added a folder that "contains additional resources for data provided by MODZCTA (modified ZIP code tabulation area) - geographic files for modified ZIP Code Tabulation Area geographies (MODZCTA)". I realize there are USPS zip codes and then there are US Census ZCTAs. Are modified ZCTAs a third type of zip code?

You have this statement: "the file ZCTA-to-MODZCTA.csv is a crosswalk showing which MODZCTA a ZIP code (or ZCTA) belongs to". Here, you are using ZCTA and zip code interchangeably. When you say MODZCTA, do you actually mean the US Census ZCTA, and ZCTA is the USPS zip code?

**Comment by mmontesanonyc** [comment]
ZCTA and ZIP code can be used somewhat interchangeably - you can think of a ZIP code as a collection of points, and a ZCTA is the area that encompasses it. You can use the numeric code to refer to the ZIP code or the ZCTA, but if you’re mapping an area, you need to use ZCTA - since a ZIP code is, strictly speaking, not an area.

MODZCTA means “modified ZCTA.” This scheme combines some areas with small populations, in order to allow more stable estimates of population size for the purposes of calculating rates. For example, in the crosswalk file you mention, you can see that the ZCTA 11451 is combined with 11433. So the MODZCTA area 11433 refers to the ZCTAs 11433 and 11451. Similarly, the MODZCTA area 11369 includes the ZCTA 11369, as well as 11371.
