### ISSUE TITLE
The Data doesn't Match the Published PDFs

### ISSUE THREAD

**Issue by platham1** [nychealth/coronavirus-data#75]
The data listed in the CASES/HOSP/DEATHS file does not match the numbers previously published on https://www1.nyc.gov/site/doh/covid/covid-19-data-archive.page. There are significant differences.
![NYC_Data_GitHub_vs_PDFS](https://user-images.githubusercontent.com/62257028/82491747-10ce4b00-9ab3-11ea-9c70-bfb54ac96b20.JPG)

**Comment by mmontesanonyc** [comment]
It looks like you are running calculations that assume that the date of report is the same as date of event, but these are different. We are reporting data based on the date of event (diagnosis, hospitalization, or death). 

189031 total cases were reported on 5/16. 190408 cases were reported on 5/17, per PDFs. The difference between these two (1377) does not represent the number of cases diagnosed i one day, but rather, additional diagnoses that occurred on many days but were reported on the 17th. 

Due to lags common to surveillance data, date of event better reflects when things actually take place. Since we are using date of event for these data, differences based on report date (and any subsequent calculations) are not valid for what has occurred in the last 24 hours.

**Comment by platham1** [comment]
Thank you for clarifying that for me.  Best regards, Paul
