### ISSUE TITLE
"NA" changes in tests-by-zcta.csv?

### ISSUE THREAD

**Issue by leafyhigh** [nychealth/coronavirus-data#80]
Hello. 

In the tests-by-zcta, what does NA (and/or 99999) mean? 

April 1 : Total for "NA" is 36
April 8 : Total for "NA" is 4811
May 11: Total for "NA" is 1953
May 12: Total for "NA" is 5607

If NA means not-yet-assigned for any zip code, and it decrease (or increase) unexpectedly though time sequence, how can we know the total number of tests in a certain day per zip code? 

(For example, some zip codes areas might not count their test numbers in a day, and then counted in the next couple of days, decreasing NA).

**Comment by mmontesanonyc** [comment]
NA means that the address was not able to be geocoded, or was missing. These data are updated as more addresses become available.

We do not recommend comparing the values in this file day-by-day because the difference between two consecutive days of data does not reflect one day of data. See other comments on the difference between report date and diagnosis date for further information on this issue.
