### ISSUE TITLE
Non-modzcta test counts included on May 23

### ISSUE THREAD

**Issue by kenteoh1** [nychealth/coronavirus-data#95]
Thanks for the timely data updates! I noticed that the May 23 update of the test_by_zcta.csv file includes data for non-modified zctas. For example, test counts for the zctas 10165, 10170, 10171, corresponding to modzcta 10017, are provided in that update. To be consistent with other days, should test counts for zctas 10165, 10170, 10171 be merged with test count for zcta 10017, or are test counts for zcta 10017 on May 23 already provided on a modified zcta basis?

**Comment by mmontesanonyc** [comment]
Yes, there was a minor reporting error that affected that file on 5/23. This was fixed in the subsequent update. 

We will note that that file doesn't show test counts _on_ 5/23, but rather, all test counts _as of_ 5/23. The subsequent file shows all test counts as of 5/24, but includes tests reported on that day but which took place over many previous days. Because of this difference between report date and event date, we regularly caution against taking the differences from daily cumulative files and treating that as daily data.

**Comment by kenteoh1** [comment]
Got it, thanks for the clarification.
