### ISSUE TITLE
Website #'s don't match totals for hospitalizations and deaths in dataset

### ISSUE THREAD

**Issue by smg7un** [nychealth/coronavirus-data#96]
https://www1.nyc.gov/site/doh/covid/covid-19-data.page

NYC.gov site doesn't match the column totals for hospitalizations and deaths.

As of 7/2/20 at 2:25 pm:

- site shows 18,519 deaths, but column only adds to 18,441
- site shows 55,045 hospitalizations, but column only adds to 53,720

**Comment by mmontesanonyc** [comment]
Yes, this is expected, though it can be confusing. 

Throughout the data in this repository, if you sum the data in one file, you may not get totals reported in another file. This is because reports for some patients have missing details - like race/ethnicity, or address, and so on. 

In this case, date of death or date of hospitalization are missing for some patients. Not all deaths have a known date of death, and not all hospitalizations have a single known date of hospitalization. As we do ongoing quality assurance on the data, we tend to find more details in other records - so these missing pieces of information get filled in over time.

**Comment by HarryBirtles** [comment]
This relates to a different question I had, but I think the same is occurring.  

Is it therefore reasonable to assume if data is more granular then it may be missing more cases too?  E.g. If I look at confirmed deaths by date from case-hosp-death.csv there are 18511 in total today, while confirmed deaths by borough and date from boro/boroughs-case-hosp-death.csv gives 18498 in total.  Presumably this is because 13 cases had dates, but not boroughs and so are missing from the second file.

Given this, would it be possible to include the data with missing attributes, with null values (or another categorization) for the attributes which are not present?
